FROM node:12.16.3 as builder

WORKDIR /home/app/web/
COPY ./package.json /home/app/web/package.json

RUN npm install

COPY . /home/app/web/.

RUN npm run build

FROM nginx:1.19

COPY --from=builder /home/app/web/build /home/app/web/build
COPY ./host.conf /etc/nginx/conf.d/default.conf
