FROM ubuntu:focal-20220105

ENV TZ=Europe/Moscow
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update
RUN apt-get install -y python3
RUN apt -y install python3-pip
RUN python3 -m pip install pybind11


RUN pip3 install boost
RUN pip3 install cmake
RUN apt-get install -y cmake libblkid-dev e2fslibs-dev libboost-all-dev libaudit-dev
RUN apt-get install -y python3-dev libxml2-dev libxslt-dev
