# Generated by Django 3.1.6 on 2021-02-16 11:02

from django.db import migrations

import core.models.user


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_processed"),
    ]

    operations = [
        migrations.AlterModelManagers(name="user", managers=[("objects", core.models.user.CustomUserManager()),],),
        migrations.RemoveField(model_name="user", name="processed",),
    ]
