# Generated by Django 3.1.7 on 2021-02-22 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_goal_goalparty"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoalPartyRequest",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("can_be_admin", models.BooleanField(default=True)),
                ("goal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.goal")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"abstract": False,},
        ),
    ]
