# Generated by Django 3.1.7 on 2021-02-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_goalpartyrequest"),
    ]

    operations = [
        migrations.AlterModelOptions(name="goalparty", options={"verbose_name_plural": "goal parties"},),
        migrations.AddField(
            model_name="goal",
            name="max_number_of_members",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
