# Generated by Django 3.1.7 on 2021-03-02 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_auto_20210222_1421"),
    ]

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=200)),
                (
                    "token_type",
                    models.CharField(
                        choices=[("EMAIL VERIFICATION", "Email Verification")],
                        default="EMAIL_VERIFICATION",
                        max_length=55,
                    ),
                ),
                ("expiration_date", models.DateTimeField()),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
