# Generated by Django 3.1.7 on 2021-03-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token_type",
            field=models.CharField(
                choices=[("EMAIL VERIFICATION", "Email Verification"), ("FORGOT PASSWORD", "Forgot Password")],
                default="EMAIL VERIFICATION",
                max_length=55,
            ),
        ),
    ]
