# Generated by Django 3.1.6 on 2021-02-18 09:37

import django.db.models.deletion
import stdimage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20210216_1402"),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", stdimage.models.StdImageField(upload_to="goal_images")),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="GoalParty",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_of_goal_party",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("goal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.goal")),
                ("members", models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={"abstract": False,},
        ),
    ]
