# Generated by Django 3.1.7 on 2021-03-10 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_auto_20210310_1342"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoalCategory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="goal_categories")),
            ],
            options={"verbose_name_plural": "goal categories",},
        ),
        migrations.RemoveField(model_name="goalpartyrequest", name="can_be_admin",),
        migrations.AlterField(
            model_name="token",
            name="token_type",
            field=models.CharField(
                choices=[("EMAIL VERIFICATION", "Email Verification"), ("FORGOT PASSWORD", "Forgot Password")],
                default="EMAIL VERIFICATION",
                max_length=55,
            ),
        ),
        migrations.AddField(
            model_name="goal",
            name="category",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="core.goalcategory"),
        ),
    ]
