# Generated by Django 3.1.7 on 2021-03-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_auto_20210312_1212"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token_type",
            field=models.CharField(
                choices=[("EMAIL VERIFICATION", "Email Verification"), ("FORGOT PASSWORD", "Forgot Password")],
                max_length=55,
            ),
        ),
    ]
