@startuml
!include <logos/nginx>
!include <logos/django>
!include <logos/flask>
!include <logos/elasticsearch>
!include <logos/redis>
!include <logos/python>
!include <logos/kafka>



title Обновлённая архитектура 1.0.0

skinparam monochrome true

actor Админ as Admin
actor Пользователь as User

node "Admin Panel" as ap{
    rectangle "<$nginx>" as admin_rp
    rectangle "<$django>\n Django" as admin_app
    database "Postgres" as admin_db

    admin_rp --> admin_app
    admin_app --> admin_db

}

node "ETL component" as etl {

    database "<$elasticsearch>" as etl_es
    rectangle "<$python>\n etl script" as etl_script

    etl_script --> etl_es
}

node "Auth API" as auth {
    rectangle "<$nginx>" as auth_rp
    rectangle "<$flask>" as auth_app
    database "<$redis>\n sessions" as auth_sessions
    database "Postgres" as auth_db

    auth_rp --> auth_app
    auth_app --> auth_db
    auth_app --> auth_sessions
}

node "Async API" as async {
    component "<$python>\n FastApi" as async_api
    rectangle "<$nginx>" as async_rp
    database "<$redis>\n cache" as async_cache

    async_rp --> async_api
    async_api --> async_cache

}

node "UGC API" as ugs {
    component "<$python>\n FastApi" as ugs_api
    rectangle "<$nginx>" as ugs_rp
    database "<$kafka>\n" as ugs_kafka
    database "Clickhouse" as ugs_clickhouse

    ugs_rp --> ugs_api
    ugs_api --> ugs_kafka
    ugs_kafka --> ugs_clickhouse

}
actor Админ as Admin
actor Пользователь as User
actor Аналитик as Analyst

left to right direction
Admin --> admin_rp
User --> auth_rp
User --> async_rp
User -->ugs_rp
Analyst <-- ugs_clickhouse

admin_db --> etl_script : etl
async_api <-- etl_es
@enduml